### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by roy1210** [KZen-networks/binance-thresh-wallet#8]
Hi teams,

I would like to install this library to my React project.
I have tried to use both Yarn and NPM, and also tried to install on both Next.js and CRA, unfortunately all shows same error.
Kindly please help to advise. Thank you!!

$ node -v
v10.17.0

Error log:
https://gist.github.com/roy1210/52b5c1b5e64c747a548877416563a7c7

**Comment by oleiba** [comment]
Which Rust version are you using?
Currently tested on rustc 1.38.0-nightly (0b680cfce 2019-07-09).
I will add that to the README.

**Comment by roy1210** [comment]
Hi,
❯ rustc -V
rustc 1.45.0 (5c1f21c3b 2020-07-13)

BTW, this is the error log when I use `npm` to isntall.
https://gist.github.com/roy1210/a23262a1c4c3cb2bdc8257687baa270d

**Comment by oleiba** [comment]
If that's possible to your application, try updating to rustc 1.38.0-nightly (0b680cfce 2019-07-09).
Can be done with
`rustup override set nightly-2019-07-10`

**Comment by roy1210** [comment]
Hi Oleliba,
I have changed rust version to rustc 1.38.0-nightly (0b680cfce 2019-07-09). However, still failed to install. Kindly refer to below error log. Thanks!

https://gist.github.com/roy1210/204d65d518a1ff31e15479655ad73315

**Comment by oleiba** [comment]
This is a general Rust compiler error.
See relevant thread here https://github.com/rust-lang/rust/issues/25289.

**Comment by roy1210** [comment]
Hi Oleiba,
I tried `brew install gcc` and then looks install this library successfully. Thank you for your help!
